name: Passing Values to Next Steps

on: workflow_dispatch

jobs:
  passing-values-bw-steps:
    runs-on: ubuntu-latest
    steps:
      - name: Set the value using ENV Vars
        run: |
          echo "variableName=this-is-the-value" >> $GITHUB_ENV

      - name: Create Variables
        id: var_source_step
        run: |
          echo "Performing a random task"
          echo "::set-output name=var1_name::Application"
          echo "::set-output name=var2_date::$(date + '%Y-%m-%d-%H-%M')"

      - name: Create Variables using Github Output
        id: unit_test
        run: |
          echo "Performing a random task"
          echo "var3_name=Application >> $GITHUB_OUTPUT"
          echo "var4_date=$(date + '%Y-%m-%d-%H-%M') >> GITHUB_OUTPUT"

      - name: Get-Variable-Value
        run: |
          echo "Printing the values"
          echo variableName: ${{ env.variableName }}
          echo var1_name: ${{ steps.var_source_step.outputs.var1_name }}
          echo var2_date: ${{ steps.var_source_step.outputs.var2_date }}
          echo content: ${{ steps.unit-test.outputs }}
          echo var3_name: ${{ steps.unit-test.outputs.var3_name }}
          echo var4_date: ${{ steps.unit-test.outputs.var4_date }}
